"""add product

Revision ID: 0db958a853e8
Revises: df142e50c5bf
Create Date: 2020-11-02 03:23:06.637162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db958a853e8'
down_revision = 'df142e50c5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sku', sa.String(length=15), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_products_id'), 'warehouse_products', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_products_id'), table_name='warehouse_products')
    op.drop_table('warehouse_products')
    # ### end Alembic commands ###
