"""add category

Revision ID: 9f041ec7eb09
Revises: 0db958a853e8
Create Date: 2020-11-02 03:37:29.329686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f041ec7eb09'
down_revision = '0db958a853e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_category_id'), 'warehouse_category', ['id'], unique=True)
    op.create_foreign_key(None, 'warehouse_products', 'warehouse_category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_products', type_='foreignkey')
    op.drop_index(op.f('ix_warehouse_category_id'), table_name='warehouse_category')
    op.drop_table('warehouse_category')
    # ### end Alembic commands ###
